{
# 公众号配置
# 公众号appId
"app_id": "wx7626d2a29f5233ad",
# 公众号appSecret
"app_secret": "9c6d8168c3a956d243a128c9be0e5295",
# 模板消息id
"template_id": "gGVZI_1ii94iM4tjVGFlaunzC2tJ-OB-8uyczOKwXUk",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["o_E5g6fY2al6NW2cGWycN6Gabr_8"],
 
# 信息配置
# 和风天气apikey
"weather_key": "e42b34059b1844868957ad13653c66f3",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦
"region": "亳州",
# 生日1，修改名字为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1": {"name": "范菲茹", "birthday": "2001-01-01"},
# 生日2
# 在一起的日子，格式同上，暂不不支持农历
"love_date": "2022-08-20",
# 金句中文，如果设置了，则会显示这里的，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}
